<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite (0)]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="5" name="Test(failed)" verbose="0">
    <classes>
      <class name="tests.selenium.TC003_CreateIncidentUsingRestAndVerifyUsingSelenium">
        <methods>
          <include name="beforeMethod"/>
          <include name="setValues"/>
          <include name="beforeClass"/>
          <include name="afterSuite"/>
          <include name="afterMethod"/>
          <include name="beforeSuite"/>
          <include name="createIncident"/>
        </methods>
      </class> <!-- tests.selenium.TC003_CreateIncidentUsingRestAndVerifyUsingSelenium -->
      <class name="tests.selenium.TC002_CreateIncidentAndGetFromRest">
        <methods>
          <include name="beforeMethod"/>
          <include name="beforeClass"/>
          <include name="afterSuite"/>
          <include name="afterMethod"/>
          <include name="setValues"/>
          <include name="beforeSuite"/>
          <include name="createIncident"/>
        </methods>
      </class> <!-- tests.selenium.TC002_CreateIncidentAndGetFromRest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite (0)] -->
